### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by bentley**
Pepys, the gift that keeps on giving.

### CODE REVIEW

**Comment by bentley** [comment]
Some of the trickier ones in b5065e0c047f2904ce2c36e3cfbd791bb27f8f52:

- plantan → plantain
- cynament → cinnamon
- terebintine → turpentine

**Comment by acabal** [comment]
For b5065e0, I think we want to keep the original spellings as they're quotations from real sources and they're far enough removed to have some flavor. `ye` -> `the` might *technically* be spelling but the appearance is so far removed from the reason that we should leave it. So I think b5065e0 can be reverted in its entirety. The rest are very good though.

In general we want to do *sound-alike* spellings updates, so things like `cynament` etc. are too old and different to qualify.

**Comment by acabal** [comment]
You can just rebase this to remove the commit and force-push to keep the history a little cleaner

**Comment by bentley** [comment]
Dropped the endnotes commit.

I do disagree on `ye`. It was pronounced “the,” not “ye,” because the first letter is actually a þ/thorn, not a y. ([See Wikipedia.](https://en.wikipedia.org/wiki/Ye_(pronoun)#Confusion_with_definite_article)) I think it should be treated as &c., etc.

**Comment by acabal** [comment]
Yes, I know. That's why I say it's *technically* correct. But in this case it's part of the flavor of the quote, and nobody but scholars and nerds like us knows that `ye` was pronounced `the`. It's certainly not pronounced that way today, in any case.

Anyway, thanks! I'm sure there will be a lot more to do on Pepys still.

**Comment by bentley** [comment]
You know it!

**Pull request merged**
