### PR TITLE
Update spellings

### PR DESCRIPTION
**Pull request by bentley**

### CODE REVIEW

**Comment by acabal** [comment]
In general, we only want sound-alike modernizations. Some of these aren't, like Aberguenny → Abergavenny, Stonage → Stonehenge. I would also not change holyday -> holiday because while it's soundalike it might not be strictly the same meaning. Can you remove those commits from this PR?

**Comment by bentley** [comment]
Abergavenny was my error, somehow I totally misread the IPA and thought they were the same…

Dropped Abergavenny and Stonehenge.

For holiday, what other meaning would there be? In the eleven cases here I didn’t see any where holyday would be either more clear or less distracting.

**Comment by acabal** [comment]
Because "holy day" and "holiday" are not sound alikes.

**Comment by bentley** [comment]
Dropped holiday.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
