### PR TITLE
[Editorial] staid -> stayed

### PR DESCRIPTION
**Pull request by tuskpot**
Out of the ~160 files containing "staid" in the SE repositories, over 100 files are in Samuel Pepys alone! Of all the 800+ occurrences, exactly one was used as an adjective and therefore preserved.

I noticed several other words that I would propose modernizing (cozen->cousin, newes->news, and so on), but I'm not going to start that project at this time.

### CODE REVIEW

**Comment by acabal** [comment]
@robinwhittleton Any interest on modernizing the rest of what @tuskpot mentioned?

**Comment by robinwhittleton** [comment]
The problem with Pepys and spelling modernisation is that it’s a bottomless pit that would take years of time, and I don’t have the technical skill to determine whether the way a word was used in the 17th century encodes a subtle difference to modern usage that would be lost if we changed it.

This PR seems reasonable. Cozen ➡️ cousin harder to make a decent judgement call on, due to the existence of “cozen” as a verb with a different meaning, and what do you about the shortened “coz”? Newes ➡️ news could be a good change to make, but again the amount of work is going to be astonomical. Overall, reaping the benefits of spelling modernisation would require most of the book to be revised, and I don’t have the time or inclination to do that.

**Comment by acabal** [comment]
OK. I think it's worthwhile pursuing some of this modernization on a as-it's-discovered basis. I think both `cozen` and `newes` are easy wins. `coz` is till modern English so no problems there. I'll take care of it. Obviously I'm not suggesting anyone re-read the entire thing looking for old spelling, but as people read it and bring things to our attention we can review them then.

**Comment by acabal** [comment]
I'll add `cozen` to the new "problem spellings" function in `se modernize-spelling` (not released yet but it's in the repo).

**Pull request merged**
